[package]
name = "untitled1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
random_str = "0.1.1"
sqlite = "0.30.4"
sql = "0.4.3"
druid = "0.8.3"
usvg = "0.29.0"
image = "0.24.5"
